# Your name and what you do
name: Francesco Taurone
bio: Automation Engineer

description: Francesco Taurone Website

# Profile picture
picture: assets/images/profile_picture.png

# your url: http://USERNAME.github.io
url: https://francescotaurone.github.io

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: mytwitter
linkedin: mylinkedin
github: mygithub
email: myemail@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: false

# add your skills here
skills-list:
    - HTML, Jade
    - CSS (Stylus, Sass, Less)
    - Javascript, NodeJS
    - AngularJS, ReactJS
    - Java, Android
    - Python
    - MySQL - MongoDB    
    - Git    

# do you want to display a projects section? true or false
projects: true
# add your projects here
project-list:
    Distributed Dual Gradient Tracking for Microgrid Control:
        name: DSC Project
        description: Control of a distributed system for Microgrid application
        url: /documents/DCS_final.pdf
    


# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
