# Your name and what you do
name: Francesco Taurone
bio: MSc student in Automation Engineering <br> University of Bologna

description: Francesco Taurone Website

# Profile picture
picture: assets/images/profile_picture.png

# your url: http://USERNAME.github.io
url: https://francescotaurone.github.io

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: tauronefra
linkedin: francescotaurone
github: francescotaurone
email: francesco.taurone@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: false

# add your skills here
skills-list:
    - HTML, Jade
    - CSS (Stylus, Sass, Less)
    - Javascript, NodeJS
    - AngularJS, ReactJS
    - Java, Android
    - Python
    - MySQL - MongoDB    
    - Git    

# do you want to display a projects section? true or false
projects: true
# add your projects here
project-list:
    DCS Project:
        name: Distributed Dual Gradient Tracking for Microgrid Control
        description: Control of a distributed multiagents system for Microgrid application
        pdf: /documents/DCS_final.pdf
        code: https://github.com/francescotaurone/Projects/tree/master/Distributed_control_smartgrid_code
    
    Robotics:
        name: Manipulator control with various trajectories and methods
        description: Control of a Puma560 manipulator by means of various control techniques 
        pdf: /documents/robotics_report.pdf
        code: https://github.com/francescotaurone/Projects/tree/master/Manipulator_simulations
    
    T3Lab:
        name: Security camera face recognition
        description: Deep learning based face recognition for safety application
        pdf: /documents/computer_vision_report.pdf
        code: https://github.com/francescotaurone/Projects/tree/master/Face_recognition
    Lejos:
        name: Lejos platform project
        description: Path following and obstacle avoidance application using LegoNXT Lejos
        code: https://github.com/francescotaurone/Projects/tree/master/Lejos_mobile_robot
      
    Thesis BSc:
        name: Bachelor thesis - AC inductor design
        description: AC inductor design for phase shifted power converter
        pdf: /documents/Bsc_Thesis_Francesco_Taurone.pdf
        
    RealTime philosophers:
        name: Real time systems project
        description: Innovative resolution of the Dining Philosophers problem for an internal university contest
        code: https://github.com/francescotaurone/Projects/blob/master/Realtime_philosophers.c
        pdf: /documents/Contest_realtime_Taurone.pdf
        
    Magna:
        name: Magna - Platform for meal sharing
        description: For the CBI project @CERN, lunch sharing service between students and elders
        url: https://cbiageing.wixsite.com/magna
        pdf: /documents/Magna_eng.pdf
   
# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
